version: "3.5"

services: 
    ruoka-api:
        build: .
        ports:
            - 3001:3001
        container_name: ruoka-api
        image: koxanybak/ruoka-api
    db:
        image: postgres
        ports: 
            - 5432:5432
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        container_name: db
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ruoka_apustaja
