version: "3.5"

services: 
    api:
        build: .
        ports:
            - 3001:3001
        container_name: ruoka-api
        image: koxanybak/ruoka-api
    db:
        image: postgres
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        container_name: ruoka-db
        environment: 
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ruoka_apustaja
    client:
        image: koxanybak/ruoka-client
        container_name: ruoka-client
    redis:
        image: redis
        container_name: ruoka-redis
